apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "daaa.fullname" . }}-arc-pv
  labels:
    {{- include "daaa.labels" . | nindent 4 }}
    pvtype: arc
spec:
  storageClassName: static
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "{{ .Values.GPFSlocal.clusterID }};{{ .Values.GPFSlocal.fileSystemID }};path={{ .Values.GPFSlocal.mainPath }}/{{ .Values.GPFSlocal.arcDir }}"
